### PR TITLE
gRPC trigger changes to be compatible with Flogo Enterprise

### PR DESCRIPTION
**Pull request by cpramodroy**
The following pull request contains changes that allow the gRPC trigger to be compatible with Flogo Enterprise.
Since there is no template, I will try and explain the changes made in each file in logical order:

### 1.  trigger/descriptor.json

- Added **"shim"** property to indicate triggers that need to run some pre-build commands. In this case, generate server stubs before generating the binary.
- Added **ref element** and updated "GRPC" to "gRPC" to be inline with the notation.
- Added a new trigger setting **"protoFile"**. If the trigger is used Flogo oss studio, then the content of the **protoFile** needs to be copied here. In case of microgateway scenarios, this field can be empty.
- Moved **"serviceName"** from trigger settings to handler settings. As each handler can refer to a rpc from any service, it makes more sense for the **serviceName** to be under handler settings.
- Change "**int**" to "**integer**" under Code element
- Added **methodField** to be **required**. I am not entirely certain if this was designed to be **"not mandatory"** for the microgateway examples but if needed we can **revert** this change and I can validation elsewhere.

### 2. trigger/metadata.go

- Again moved **"serviceName"** from trigger settings to handler settings and added **"protoFile"** to trigger settings.
- Set required tags for **methodName** and **serviceName** which can be avoided if it causes tests to break.

### 3. trigger/shim/build.go

- This is the prebuild that is run (because of the the shim tag in descriptor.json) to generate the server stubs for a given proto file. It collects data from the flogo.json that is being built.
- Server and client templates are the same as what is seen in **grpcservicegen.go**.

### 4. trigger/trigger.go

- Changed  **"logger"** to be **"Logger"**(exported) to allow access in the generated server stubs. The server template in **build.go** will access the **Logger** as "**s.trigger.Logger.Debug**" and "**s.trigger.Logger.Error**"
- Changed the key in handler map to be "**ServiceName +"_" + MethodName**" since **serviceName** is now at the handler setting level
- Added **return err** statements to prevent the engine from continuing to execute when an error occurs.
- Iterating over the list of serviceNames and registering each "**ServiceName + protoName**" combination.
- Certain field names (message names and service names included) in proto files are converted to their json equivalent by default. So for example "**first_name**" would be converted to "**firstName**". To keep the same case of the field names as seen in the proto files, we access the field names using the "**GetProperties()**" method in the **proto** package. "**OrigName**" refers to the actual name of the field in the proto file.
- Also ignoring any fields with prefix "**XXX_**" as those are generated field names and need not be mapped.
- In cases where the proto field is a **proto message type**, the values have to be serialized using the "**jsonpb marshaler**" that is part of the **protobuf** package. The previous implementation would break if there were nested "**one of**" types inside messages. jsonpb marshaler handles all such cases by making use of the generated struct tags.
- grpcData map now includes "**serviceName**" as we will see in the server stub template changes.
- Added couple of **return err** statements where necessary.

### 5. trigger_test.go

- Made changes to be inline with moving **serviceName** from trigger settings to handler settings.

### 6. support/grpcservicegen.go

- Edited server template to include "**serviceName**" as part of "**grpcData**".
- Similar to **trigger.go**, used "**jsonpb.UnmarshalString()**" instead of "**json.Unmarshal()**" to support the right way to unmarshal gRPC payload.
- When building service names and method names, used "**generator.CamelCase()**" to convert **only** **Method** and **Service Names** to be its json equivalent value. This is because when creating generating the tree mapping for input and output Flogo Enterprise uses **protobuf-js** that provides an option to **keep the case** for all field names but converts all Method Names and Service Names to their json equivalent. So a service or method name will be converted from **camel_case** to **Camel_Case**. More examples can be seen in the **generator** package under the "**CamelCase**" function. The old implementation would fail in such scenarios. The only catch however is, today we do not support service names or method names that begin with **"_"**.

### 7. Rest of the files

- Rest of the files include changes primarily to move the "**serviceName**" setting from trigger level to handler level
- Updating the example's generated server stubs to be inline with the changes we made to the server template. Like adding the jsonpb package, adding serviceName to grpcData and using jsonpb.UnmarshalString()

### CODE REVIEW

**Comment by pointlander** [comment]
'go test -p 1 ./...' doesn't pass:
`--- FAIL: TestGRPCTrigger (0.00s)
    trigger_test.go:78: 
        	Error Trace:	trigger_test.go:78
        	Error:      	Expected nil, but got: &errors.errorString{s:"field 'serviceName' is required"}
        	Test:       	TestGRPCTrigger
    trigger_test.go:87: 
        	Error Trace:	trigger_test.go:87
        	Error:      	Expected nil, but got: &status.statusError{Code:12, Message:"unknown service grpc2grpc.PetStoreService", Details:[]*any.Any(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
        	Test:       	TestGRPCTrigger
    trigger_test.go:88: 
        	Error Trace:	trigger_test.go:88
        	Error:      	Should be true
        	Test:       	TestGRPCTrigger
FAIL
FAIL	github.com/project-flogo/grpc	0.015s
?   	github.com/project-flogo/grpc/activity	[no test files]
2019/07/25 16:31:28 Starting server on port:  :9000
--- FAIL: TestGRPC2GRPCAPI (0.00s)
    example_test.go:97: 
        	Error Trace:	example_test.go:97
        	Error:      	Expected nil, but got: &errors.errorString{s:"error creating trigger instances - value '' is not valid"}
        	Test:       	TestGRPC2GRPCAPI
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa2dc9a]

goroutine 5 [running]:
testing.tRunner.func1(0xc000044600)
	/usr/local/go/src/testing/testing.go:830 +0x392
panic(0xae9860, 0x11f6020)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/project-flogo/grpc/examples.testGRPC2GRPC(0xc000044600, 0x0, 0x0)
	/home/andrew/tibco/cpramodroy/grpc/examples/example_test.go:37 +0x18a
github.com/project-flogo/grpc/examples.TestGRPC2GRPCAPI(0xc000044600)
	/home/andrew/tibco/cpramodroy/grpc/examples/example_test.go:98 +0xa8
testing.tRunner(0xc000044600, 0xbfb130)
	/usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x35a
FAIL	github.com/project-flogo/grpc/examples	0.015s`

**Comment by cpramodroy** [comment]
I think the first part is because serviceName and methodName were marked as mandatory in descriptor.json and metadata.go. I fixed that part. When I try to run 'go test -p 1 ./...' there is no response from the console. I tried to run 'go test -p 1 short ./...' as well. Anything I might be missing here?

**Comment by pointlander** [comment]
I am still getting errors by running  'go test -p 1 ./...' in the root of the project directory.

**Comment by pointlander** [comment]
Output without any errors should look like this:
`go test -p 1 ./...
ok  	github.com/project-flogo/grpc	0.014s
?   	github.com/project-flogo/grpc/activity	[no test files]
ok  	github.com/project-flogo/grpc/examples	22.093s
?   	github.com/project-flogo/grpc/examples/api/grpc-to-grpc	[no test files]
?   	github.com/project-flogo/grpc/examples/api/grpc-to-rest	[no test files]
?   	github.com/project-flogo/grpc/examples/api/rest-to-grpc	[no test files]
?   	github.com/project-flogo/grpc/examples/json/grpc-to-grpc	[no test files]
?   	github.com/project-flogo/grpc/examples/json/grpc-to-rest	[no test files]
?   	github.com/project-flogo/grpc/examples/json/rest-to-grpc	[no test files]
?   	github.com/project-flogo/grpc/proto/grpc2grpc	[no test files]
?   	github.com/project-flogo/grpc/proto/grpc2rest	[no test files]
?   	github.com/project-flogo/grpc/proto/rest2grpc	[no test files]
?   	github.com/project-flogo/grpc/support	[no test files]
?   	github.com/project-flogo/grpc/trigger	[no test files]
?   	github.com/project-flogo/grpc/util	[no test files]`

**Comment by cpramodroy** [comment]
Fixed the tests by changing the case of param fields to lowercase. The only part I didn't check in was commenting out Drain() method under the util package. For me the loop was running infinitely and that's the reason I wasn't able to run the tests. But since you are able to run the tests without commenting out Drain(), I am leaving it as is. Here's the snapshot of the test results.
image

**Review by pointlander — APPROVED** [review]

**Comment by pointlander** [comment]
thanks!

**Pull request merged**
