### PR TITLE
fix grpc go test

### LINKED ISSUE #2: TestGRPC2RestAPI  go tests failing
github.com/project-flogo/grpc/examples/TestGRPC2RestAPI (680ms)
go test -v github.com/project-flogo/grpc/examples -run ^TestGRPC2RestAPI$
panic: interface conversion: interface {} is nil, not *grpc2rest.PetResponse
/home/lmekala/.go/src/testing/testing.go:792 +0x387
/home/lmekala/.go/src/runtime/panic.go:513 +0x1b9
/home/lmekala/go/src/github.com/project-flogo/grpc/examples/example_test.go:128 +0x5e2
/home/lmekala/go/src/github.com/project-flogo/grpc/examples/example_test.go:149 +0xa9
/home/lmekala/.go/src/testing/testing.go:827 +0xbf
/home/lmekala/.go/src/testing/testing.go:878 +0x353

### PR DESCRIPTION
**Pull request by nareshkumarthota**
This PR fixes #2 

Resolution:
Changed test cases execution order.
Push test case executes first then get test case executed, so that pet will be always available from petstore.

### CODE REVIEW

**Review by rameshpolishetti — CHANGES_REQUESTED** [review]
@nareshkumarthota still there is a chance that someone might update the per/user data these test cases depend on, which could lead to test case fail again. My suggestion is to have more generic assertions like on error, response codes OR data types, etc... but not on data.

**Comment by nareshkumarthota** [comment]
@rameshpolishetti  requested changes implemented. Local server is used instead of petstore.

**Comment by rameshpolishetti** [comment]
@nareshkumarthota changing the endpoint URL petstore.swagger.io to localhost will impact the new user to run examples provided, consider adding/updating required test data into petstore before the TEST run.

**Comment by nareshkumarthota** [comment]
I will resubmit the PR with the required changes.

**Pull request closed without merging**
